<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Support Message - Fairtrade Loans</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .email-container {
            width: 100%;
            padding: 20px;
            background-color: #ffffff;
            max-width: 600px;
            margin: 20px auto;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        .email-header {
            background-color: #00bcd4;
            color: white;
            text-align: center;
            padding: 20px 0;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
        }
        .email-header h2 {
            margin: 0;
        }
        .email-content {
            padding: 20px;
            text-align: left;
            line-height: 1.6;
            color: #333;
        }
        .email-content p {
            margin: 10px 0;
        }
        .support-details {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .support-details th, .support-details td {
            border: 1px solid #dddddd;
            padding: 12px;
            text-align: left;
        }
        .support-details th {
            background-color: #e7fcff;
            font-weight: bold;
            width: 120px;
        }
        .message-content {
            background-color: #f9f9f9;
            border: 1px solid #e0e0e0;
            border-radius: 5px;
            padding: 15px;
            margin: 15px 0;
            white-space: pre-wrap;
            font-family: 'Courier New', monospace;
        }
        .email-footer {
            margin-top: 20px;
            font-size: 12px;
            color: #888;
            text-align: center;
            border-top: 1px solid #f4f4f4;
            padding-top: 10px;
        }
        .email-footer p {
            margin: 5px 0;
        }
        .logo-container {
            text-align: center;
            margin-bottom: 20px;
        }
        .priority-notice {
            background-color: #fff3cd;
            border: 1px solid #ffeaa7;
            border-radius: 5px;
            padding: 10px;
            margin: 15px 0;
            color: #856404;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="logo-container">
            <img src="{{ asset('fairtrade-logo.png') }}" alt="Fairtrade Logo" style="max-height: 80px;">
        </div>
        <div class="email-header">
            <h2>New Support Message Received</h2>
        </div>
        <div class="email-content">
            <div class="priority-notice">
                <strong>📩 New Support Request</strong> - A customer has submitted a support message through the Fairtrade Loans application.
            </div>

            <p>Hello Support Team,</p>
            <p>A new support message has been received. Please review the details below and respond promptly:</p>

            <table class="support-details">
                <tr>
                    <th>From:</th>
                    <td><strong>{{ $supportData['name'] }}</strong></td>
                </tr>
                <tr>
                    <th>Email:</th>
                    <td><a href="mailto:{{ $supportData['email'] }}">{{ $supportData['email'] }}</a></td>
                </tr>
                <tr>
                    <th>Subject:</th>
                    <td><strong>{{ $supportData['subject'] }}</strong></td>
                </tr>
                <tr>
                    <th>Submitted:</th>
                    <td>{{ now()->format('F j, Y \a\t g:i A') }}</td>
                </tr>
            </table>

            <p><strong>Message Content:</strong></p>
            <div class="message-content">{{ $supportData['message'] }}</div>

            <p><strong>Next Steps:</strong></p>
            <ul>
                <li>Reply directly to this email to respond to the customer</li>
                <li>Use the customer's email address: <strong>{{ $supportData['email'] }}</strong></li>
                <li>Reference the subject line for context</li>
            </ul>

            <p>Best regards,<br>
            <strong>Fairtrade Loans Support System</strong></p>
        </div>
        <div class="email-footer">
            <p>This email was automatically generated by the Fairtrade Loans Support System.</p>
            <p>Please do not reply to this automated message. Reply directly to the customer using their email address above.</p>
            <p>&copy; {{ date('Y') }} Fairtrade Loans. All rights reserved.</p>
        </div>
    </div>
</body>
</html>